### ISSUE TITLE
Odevzdávám první úkol

### ISSUE THREAD

**Issue by helenaKuthanova** [helenaKuthanova/python_data_science#1]
@AnetaPopelova Můžu poprosit o kontrolu? Děkuji!

**Comment by pesikj** [comment]
Ahoj @helenaKuthanova,

omlouváme se za zpoždění. Úkol je zpracovaný moc hezky.

Bodový graf je v pořádku, ale já bych doporučil v tomto případě držet se toho, že sloupec `Y` bude na vodorovné ose. Sice jde o korelaci, ale protože se chystáme na regresi, už bych dával `Y` na svislou osu, protože to tak bude srozumitelnější.

```
sns.scatterplot(data=data_corr, x="Y", y="FL")
```

Jinak je vše správně naprogramováno i okomentováno, takže super :-)

**Comment by helenaKuthanova** [comment]
Děkuju moc!
